version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-216-185-51.eu-west-1.compute.amazonaws.com
            port: '5432'
            database: d9qj4kqih0ksor
            ssl: true
            user: thbxpbmkgjdsex
            password: a006a90d48ca554e7ec278f8f43bffc1377a54433772a1368c0e30aaa70bbc8e
            migrations: true